import { useState, useEffect } from "react";
import { Navigation } from "@/components/Navigation";
import { Button } from "@/components/ui/button";
import { Download, FileText, TrendingDown, Target, HelpCircle } from "lucide-react";

// Module-level cache — survives page navigation within the SPA
let _reportCache: any = null;

export default function Report() {
  const [reportData, setReportData] = useState<any>(_reportCache);

  useEffect(() => {
    if (_reportCache) return; // already loaded
    const fetchReport = async () => {
      try {
        const res = await fetch('/api/report');
        const data = await res.json();
        _reportCache = data;
        setReportData(data);
      } catch (err) {
        console.error(err);
      }
    };
    fetchReport();
  }, []);

  if (!reportData) return <div className="min-h-screen bg-background pt-28 text-center">Loading Report...</div>;
  if (reportData.error) return <div className="min-h-screen bg-background pt-28 text-center text-destructive">Error: {reportData.error}</div>;

  return (
    <div className="min-h-screen bg-background">
      <Navigation />
      
      <main className="container mx-auto px-6 pt-28 pb-20">
        <div className="flex flex-col md:flex-row md:items-center justify-between mb-8 gap-4">
          <div>
            <h1 className="text-3xl font-bold mb-2">AI Financial Report</h1>
            <p className="text-muted-foreground">Generated by GLM-4 based on your historical data.</p>
          </div>
          <Button className="bg-primary hover:bg-primary/90 text-white">
            <Download className="w-4 h-4 mr-2" />
            Export as PDF
          </Button>
        </div>

        {/* --- MOCK DATA FOR UI DEMO: STATIC REPORT VIEW --- */}
        <div className="bg-card border border-border shadow-glow rounded-xl p-8 max-w-4xl mx-auto">
          
          {/* Header */}
          <div className="border-b border-border pb-6 mb-6 flex items-center space-x-4">
            <div className="w-12 h-12 bg-primary/20 rounded-lg flex items-center justify-center">
              <FileText className="text-primary w-6 h-6" />
            </div>
            <div>
              <h2 className="text-2xl font-bold">Executive Summary: Q2 2026</h2>
              <p className="text-muted-foreground">Prepared on April 20, 2026</p>
            </div>
          </div>

          {/* 1. Financial Summary */}
          <section className="mb-8">
            <h3 className="text-xl font-bold mb-4 font-sans border-b border-border/50 pb-2">1. Financial Summary</h3>
            <div className="grid grid-cols-3 gap-4 mb-4">
              <div className="bg-background border border-border rounded-lg p-4">
                <p className="text-sm text-muted-foreground mb-1">Total Revenue</p>
                <p className="text-xl font-bold text-emerald-400">${reportData.summary.revenue.toFixed(2)}</p>
              </div>
              <div className="bg-background border border-border rounded-lg p-4">
                <p className="text-sm text-muted-foreground mb-1">Total Expenses</p>
                <p className="text-xl font-bold text-destructive">${reportData.summary.expenses.toFixed(2)}</p>
              </div>
              <div className="bg-background border border-border rounded-lg p-4">
                <p className="text-sm text-muted-foreground mb-1">Net Profit</p>
                <p className="text-xl font-bold text-primary">${reportData.summary.profit.toFixed(2)}</p>
              </div>
            </div>
            <p className="text-sm leading-relaxed text-foreground/90">
              The business shows a healthy margin of 55% over the last quarter. Revenue has steadily grown month-over-month. However, expenses have spiked by 12% in the most recent month due to sudden software subscription renewals and contractor payments.
            </p>
          </section>

          {/* 2. Key Issues Identified */}
          <section className="mb-8">
            <h3 className="text-xl font-bold mb-4 font-sans text-destructive flex items-center border-b border-border/50 pb-2">
              <TrendingDown className="w-5 h-5 mr-2" />
              2. Key Issues Identified (AI Analysis)
            </h3>
            <ul className="space-y-3 list-disc pl-5 text-sm text-foreground/90">
              {reportData.issues.map((issue: string, idx: number) => (
                <li key={idx}><strong className="text-foreground">Issue {idx + 1}:</strong> {issue}</li>
              ))}
            </ul>
          </section>

          {/* 3. Recommended Actions */}
          <section className="mb-8">
            <h3 className="text-xl font-bold mb-4 font-sans text-emerald-400 flex items-center border-b border-border/50 pb-2">
              <Target className="w-5 h-5 mr-2" />
              3. Recommended Actions
            </h3>
            <div className="space-y-4">
              {reportData.recommendations.map((rec: string, idx: number) => (
                <div key={idx} className={`${idx % 2 === 0 ? 'bg-emerald-500/10 border-emerald-500/20 text-emerald-500' : 'bg-primary/10 border-primary/20 text-primary'} border rounded-lg p-4`}>
                  <h4 className="font-bold mb-1">Action {idx + 1}</h4>
                  <p className="text-sm text-foreground">{rec}</p>
                </div>
              ))}
            </div>
          </section>

          {/* 4. Forecasted Outcomes */}
          <section className="mb-8">
            <h3 className="text-xl font-bold mb-4 font-sans text-blue-400 flex items-center border-b border-border/50 pb-2">
              <HelpCircle className="w-5 h-5 mr-2" />
              4. Forecasted Outcomes
            </h3>
            <p className="text-sm text-foreground/90 leading-relaxed bg-background border border-border p-4 rounded-lg">
              {reportData.outcomes}
            </p>
          </section>
          
          <div className="text-xs text-muted-foreground text-center mt-12 pt-4 border-t border-border">
            Note: This report is generated by AI and is not a substitute for professional financial advice.
          </div>

        </div>
      </main>
    </div>
  );
}
